# Generated by Django 4.2.5 on 2023-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
